paths:
  /api/transactions:
    post:
      security:
        - JWTAuth: []
      tags:
        - Transactions
      summary: Create a new transaction
      description: Creating a new course purchase transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionCreateReturn"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/TokenRequired"

