components:
  schemas:
    Admins:
      type: object
      required:
        - name
        - email
        - password
      properties:
        id:
          type: string
          readOnly: true
          example: 227af912-87f0-4cbd-ab6a-d9120e2c2a6b
        name:
          type: string
          example: Jhon Wick
        email:
          type: string
          example: jwparabellum@email.com
        password:
          type: string
          example: jw1234
    Login:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: jwparabellum@email.com
        password:
          type: string
          example: jw1234
    UpdateUserProfile:
      type: object
      required:
        - password
        - isSeller
      properties:
        password:
          type: string
          example: jw1234
        isSeller:
          type: boolean
          example: "false"
    GetAllUsers:
      type: array
      items:
        $ref: "#/components/schemas/UsersCreateReturn"
    AdminGetAllCourses:
      type: array
      items:
        $ref: "#/components/schemas/CourseCreateReturn"
    ProfileAdminReturn:
      type: object
      properties:
        id:
          type: string
          example: e54a5499-9a64-4dc9-8def-0a192e5cafff
        name:
          type: string
          example: Jhon Wick
        email:
          type: string
          example: jwparabellum@email.com
    AdminUpdateUserIsSeller:
      type: object
      properties:
        status:
          type: boolean
          example: "false"
    AdminUpdateCourse:
      type: object
      properties:
        status:
          type: string
          example: APPROVED
    AdminUpdateCourseReturn:
      type: object
      properties:
        message:
          type: string
          example: Course status updated successfully
    AdminDeleteUser:
      type: object
      properties:
        message:
          type: string
          example: User deleted successfully
    LoginAdminReturn:
      type: object
      properties:
        accessToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU1NGE1NDk5LTlhNjQtNGRjOS04ZGVmLTBhMTkyZTVjYWZmZiIsImlhdCI6MTcxNTI5OTg5MywiZXhwIjoxNzE1OTA0NjkzfQ.h7f_jbduxm59eVw_MaCkCHJRkq2Hdt0EGTyDdZXmdiU
        user:
          type: object
          properties:
            id:
              type: string
              example: e54a5499-9a64-4dc9-8def-0a192e5cafff
            name:
              type: string
              example: Jhon Wick
            email:
              type: string
              example: jwparabellum@email.com
    AdminsCreateReturn:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          example: 227af912-87f0-4cbd-ab6a-d9120e2c2a6b
        name:
          type: string
          example: Jhon Wick
        email:
          type: string
          example: jwparabellum@email.com